Week1/youngjae/B1074.java, Week1/youngjae/B10809.java, Week1/youngjae/B10828.java, Week1/youngjae/B10845.java, Week1/youngjae/B11050.java, Week1/youngjae/B1546.java, Week1/youngjae/B1920.java, Week1/youngjae/B1978.java, Week1/youngjae/B2609.java, Week1/youngjae/B7576.java
=> [Week1] 송영재 브론즈 실버 제출

.gitignore, Week1/gyumin/.gitignore, Week1/gyumin/gyumin/B1074.java, Week1/gyumin/gyumin/B10809.java, Week1/gyumin/gyumin/B10828.java, Week1/gyumin/gyumin/B10845.java, Week1/gyumin/gyumin/B11050.java, Week1/gyumin/gyumin/B1546.java, Week1/gyumin/gyumin/B1920.java, Week1/gyumin/gyumin/B1978.java, Week1/gyumin/gyumin/B2609.java, Week1/gyumin/gyumin/B7576.java
문제 풀이 목록
문제1 (링크: (https://www.acmicpc.net/problem/10809))
- 입력받은 문자를 char [] 로 변환 후, idx와 아스키 코드를 활용해 풀이
문제2 (링크: (https://www.acmicpc.net/problem/2609))
1) a > b 일 때, a / b 연산을 b와 a % b로 바꿔가며 계속 진행
2) a % b가 0 이면 a로 교환된 이전 연산의 나머지가 최대공약수
// 1, 2번 과정이 유클리드 호제법
3) a * b를 최대공약수로 나누면 최소공배수
문제3 (링크: (https://www.acmicpc.net/problem/1978))
- 소수의 배수는 무조건 합성수라는 개념을 이용한 에라토스테네스의 체를 이용하는 문제
- 배열의 idx를 수 범위 자체로 치환 후, 합성수의 값을 먼저 지우고 그 배열과 조건문을 이용
문제4 (링크: (https://www.acmicpc.net/problem/11050))
- 이항계수 연산식인 n! / (r! * (n - r)!) 을 처리하기 위해 조건문을 활용하여 팩토리얼 연산을 진행하는 문제
문제5(링크: (https://www.acmicpc.net/problem/1546))
- 배열에 점수를 등록한 뒤, 최고점을 탐색하는 문제
- 최고점을 탐색한 후에는 조건에 맞추어 전체 점수를 갱신한 뒤 평균을 출력
기타
코드 리뷰 부탁드립니다!
=> [Week1] 김규민 브론즈, 실버 제출

Week1/huimang/B1074.java, Week1/huimang/B10809.java, Week1/huimang/B10828.java, Week1/huimang/B10845.java, Week1/huimang/B11050.java, Week1/huimang/B1546.java, Week1/huimang/B1920.java, Week1/huimang/B1978.java, Week1/huimang/B2609.java, Week1/huimang/B7576.java
1. 알파벳 찾기 (링크: https://www.acmicpc.net/problem/10809)
- 배열 탐색을 하며 알파벳 찾기 -> char 알파벳 값 빼기
2. 최대공약수와 최소공배수 (링크: https://www.acmicpc.net/problem/2609)
- 반복문을 이용한 최대 공약수 및 최소 공배수 찾기
3. 소수 찾기 (링크: https://www.acmicpc.net/problem/1978)
- 반복문을 이용한 소수 찾기 -> 1과 자신을 약수로 갖는 수
4. 이항 계수 1 (링크: https://www.acmicpc.net/problem/11050)
- n!/(n-k)! * k! 계산하기.. 현재도 이항 계수가 뭐 하는건지 잘 모르겠음..
5. 평균 (링크: https://www.acmicpc.net/problem/1546)
- 반복문을 이용한 최댓값  찾기 및 값 변경, 평균 구하기.
- 코드 리뷰 부탁드립니다!
=> [Week1] 김희망 브론즈 제출

Week1/mini9922g/B1074.java, Week1/mini9922g/B10809.java, Week1/mini9922g/B10828.java, Week1/mini9922g/B10845.java, Week1/mini9922g/B11050.java, Week1/mini9922g/B1546.java, Week1/mini9922g/B1920.java, Week1/mini9922g/B1978.java, Week1/mini9922g/B2609.java, Week1/mini9922g/B7576.java
1. **[10809 - 알파벳 찾기](https://www.acmicpc.net/problem/10809)**  
- 입력받은 단어에서 a-z까지 indexOf를 사용해 등장 위치를 찾았습니다
2. **[2609 - 최대공약수와 최소공배수](https://www.acmicpc.net/problem/2609)**  
- 나눴을때 0이되는 수를 반복문을 통해 구해 최대공약수를 구하고 최소공배수를 구했습니다
3. **[1978 - 소수 찾기](https://www.acmicpc.net/problem/1978)**  
- 반복문을 통해 약수가 2개일경우 소수의 개수를 +1 했습니다
4. **[11050 - 이항 계수 1](https://www.acmicpc.net/problem/11050)**  
- N!/k!(N-K)! 를 사용했습니다
5. **[1546 - 평균](https://www.acmicpc.net/problem/1546)**  
- 점수를 배열에 입력받고 가장 큰 수를 구해 조작된 점수배열을 만들어 평균을 구했습니
---
1. **[10828 - 스택](https://www.acmicpc.net/problem/10828)**  
- Stack과 if문을 사용했습니다
2. **[10845 - 큐](https://www.acmicpc.net/problem/10845)**  
- Deque와 if문을 사용했습니다
3. **[1920 - 수 찾기](https://www.acmicpc.net/problem/1920)**  
- 재귀함수로 구현해본 후 메모리 초과 이슈로 새로 풀었습니다
- while을 통해서 …
=> [Week1] 강창민 브론즈, 실버 제출

Week1/jimin/B10809.java, Week1/jimin/B11050.java, Week1/jimin/B1546.java, Week1/jimin/B1978.java, Week1/jimin/B2609.java
1. 알파벳 찾기 (링크: https://www.acmicpc.net/problem/10809)
- 알파벳을 string 으로 저장하고, BufferedReader로 단어 S를 한줄로 입력받아 해당 알파벳이 단어에 포함되어 있다면 그 위치를 출력, 포함되어 있지 않다면 -1 출력
2. 최대공약수와 최소공배수 (링크: https://www.acmicpc.net/problem/2609)
- 유클리드 호제법 공식을 활용하여 최대공약수를 메서드로 작성 풀
3. 소수 찾기 (링크: https://www.acmicpc.net/problem/1978)
- 소수 판별 (isPrime) 메서드를 작성하여 풀이
4. 이항 계수 1 (링크: https://www.acmicpc.net/problem/11050)
- 공식(n!/(n-k)!*k! 을 사용하여 문제 풀이
5. 평균 (링크: https://www.acmicpc.net/problem/1546)
- 시험 점수를 배열에 담아서 문제 풀이
- 늦게 제출해서 죄송합니다 . . . 다음주부터는 기한 잘 지키겠습니다 . . 한 번만 봐주세요 (리뷰는 다른분꺼 올려주신걸로 참고하겠습니다)
=> [Week1] Add solutions

Week2/huimang/B10820.java, Week2/huimang/B10824.java, Week2/huimang/B1157.java, Week2/huimang/B1212.java, Week2/huimang/B1259.java, Week2/huimang/B12820.java, Week2/huimang/B1541.java, Week2/huimang/B17609.java, Week2/huimang/B2470.java, Week2/huimang/B2559.java, Week2/huimang/B3273.java
1. 네 수 (링크: https://www.acmicpc.net/problem/10824)
- 정수형의 범위를 생각하며 파싱하기.
2. 8진수 2진수 (링크: https://www.acmicpc.net/problem/1212)
- BigInteger를 이용한 8진수 2진수 변환.. 아쉽게도 시간은 고려하지 않았습니다..
3. 문자열 분석 (링크: https://www.acmicpc.net/problem/10820)
- 조건문과 반복문을 이용한 풀이
4. 단어 공부 (링크: https://www.acmicpc.net/problem/1157)
- 에초부터 들어온 문자열을 모두 대문자로 변환하자! 그리고 카운팅 배열을 이용한.. 풀이 
5. 팰린드롬수 (링크: https://www.acmicpc.net/problem/1259)
- 수업시간에 배운 양쪽 끝에서 부터 체크하는 회문 검사!
- 8진수 2진수 좀 더 시간을 쏟을 것을 후회가 되네여... 바쁜 일이 정리되면... 성실히.. 
- 다들 시험 화이팅 입니다!
- 코드 리뷰 부탁드립니다!
=> [Week2] 김희망 브론즈 제출

Week2/강창민/B10820.java, Week2/강창민/B10824.java, Week2/강창민/B1157.java, Week2/강창민/B1212.java, Week2/강창민/B1259.java, Week2/강창민/B1541.java, Week2/강창민/B17609.java, Week2/강창민/B2470.java, Week2/강창민/B2559.java, Week2/강창민/B3273.java
1.  네 수 (링크 : https://www.acmicpc.net/problem/10824)
- String으로 입력받고 숫자 연결 후 Long으로 변환하여 더하기
2. 8진수 2진수 (링크 : https://www.acmicpc.net/problem/1212)
- 8진수 각 자리를 2진수로 변환하여 출력
3. 문자열 분석 (링크 : https://www.acmicpc.net/problem/10820)
- 문자열 각 위치를 charAt을 활용하여 비교하여 개수 세기
4. 단어 공부 (링크 : https://www.acmicpc.net/problem/1157)
- 대문자로 변환 후 카운팅, 이후 결과에 따라 출력
5. 팰린드롬수 (링크 : https://www.acmicpc.net/problem/1259)
- 문자열로 받고 팰린드롬 확인
6. 수열 (링크 : https://www.acmicpc.net/problem/2559)
- 투포인터로 구현(근데 실행시간 보니까 슬라이딩 윈도우가 맞는거 같아요)
7. 두 수의 합 (링크 : https://www.acmicpc.net/problem/3273)
- 투포인터로 숫자를 조절해가며 탐색
8. 잃어버린 괄호 (링크 : https://www.acmicpc.net/problem/1541)
- 첫  빼기(-) 가 나오기 전까지 더하고 그 이후로는 모든 수를 뺌 
- 골드 문제는 투포인터랑 슬라이딩 윈도우에 익숙해지면 풀어보려고요....
- 리뷰 부탁드립니다
=> [Week2] 강창민 브론즈 실버 제출

Week2/jimin/B10820.java, Week2/jimin/B10824.java, Week2/jimin/B1157.java, Week2/jimin/B1212.java, Week2/jimin/B1259.java
[10820 - 문자열 분석](https://www.acmicpc.net/problem/10820)
- 1차원 배열 count 선언하여 0: 소문자 개수, 1: 대문자 개수, 2: 숫자 개수, 3: 나머지(공백) 개수 저장 
- String 으로 한 줄씩 입력받아 toCharArray를 이용하여 한 문자씩 체크하면서 해당하는 것에 count++
[10824 - 네 수](https://www.acmicpc.net/problem/10824)
- A, B, C, D 모두 숫자의 범위가 크기 때문에 long으로 선언
- StringTokenizer를 이용하여 한 단어씩 받아와 long 타입의 변수에 저장
- String.valueOf() 사용하여 문자열로 변환 후 출력
[1157 - 단어 공부](https://www.acmicpc.net/problem/1157)
- HashMap 사용하여 key: 문자, value: 문자 개수 count하여 저장
- boolean 타입의 중복 여부를 체크하여 중복일 때 '?' 아닐 때 최빈 문자 출력
[1212 - 8진수 2진수](https://www.acmicpc.net/problem/1212)
- 가능하면 500ms 이내 풀어보기 미션 달성 -> 424ms
- 8진수를 String 타입으로 받아와 한 문자씩 체크하면서 10진수로 변경 후Integer.toBinaryString()을 사용하여 2진수로 변환
- 첫번째 숫자가 아니면서, 2진수의 길이가 2이면 앞에 "0" 추가
- 첫번째 숫자가 아니면서, 2진수의 길이가 1이면 앞에 "00" 추가
[1259 - …
=> [Week2] 이지민 브론즈 제출

Week2/이창열/B10820.java, Week2/이창열/B10824.java, Week2/이창열/B1157.java, Week2/이창열/B1212.java, Week2/이창열/B1259.java
1. **[10824 - 네 수](https://www.acmicpc.net/problem/10824)**  
- 네 자연수 A, B, C, D가 주어질 때, A와 B를 붙인 수와 C와 D를 붙인 수의 합을 구합니다.
2. **[1212 - 8진수 2진수](https://www.acmicpc.net/problem/1212)**  
- 8진수를 2진수로 변환합니다. 0이 아닌 경우 반드시 1로 시작해야 합니다.
3. **[10820 - 문자열 분석](https://www.acmicpc.net/problem/10820)**  
- 주어진 문자열에 포함된 소문자, 대문자, 숫자, 공백의 개수를 각각 계산합니다.
4. **[1157 - 단어 공부](https://www.acmicpc.net/problem/1157)**  
- 단어에서 가장 많이 사용된 알파벳을 대문자로 출력합니다. 가장 많이 사용된 알파벳이 여러 개라면 `?`를 출력합니다.
5. **[1259 - 팰린드롬수](https://www.acmicpc.net/problem/1259)**  
- 주어진 수가 팰린드롬수인지 확인합니다. (무의미한 0은 고려하지 않습니다)
코드 리뷰 부탁드립니다!
=> [Week2] 이창열 브론즈 제출

Week3/Jimin/B10798.java, Week3/Jimin/B1260.java, Week3/Jimin/B2566.java, Week3/Jimin/B2738.java
[1260 - DFS와 BFS](https://www.acmicpc.net/problem/1260)
- 재성이 코드 + 인터넷 코드를 보면서 이해하려고 해도 완벽하게 이해하진 못했음 . .
- DFS ->재귀 활용 (그나마 이게 젤 이해가 됨)
- BFS -> 큐 활용 (큐 자체를 내가 잘 이해하지 못하는 것 같은지 여긴 진짜 모르겠음)
[10798 - 세로읽기](https://www.acmicpc.net/problem/10798)
- 한 줄씩 String 으로 입력받은 뒤, 젤 문자열이 긴 숫자만큼 돌면서 세로로 출력
- 문자열의 길이가 현재 idx 보다 작거나 같은 경우 continue
[2738 - 행렬 덧셈](https://www.acmicpc.net/problem/2738)
- 첫번째 배열 입력 받은 뒤, 두번째 배열 입력받을 때 첫번째 배열에 바로 더해서 출력
[2566 - 최댓값](https://www.acmicpc.net/problem/2566)
- 2차원 배열에 저장할 때 최댓값, 최대값의 열, 최댓값의 행을 입력받아서 출력
- 코드 리뷰 부탁드립니다! :-)
=> [Week3] 이지민 브론즈, 실버 1문제 제출

Week3/ChangYeol/B10798.java, Week3/ChangYeol/B11725.java, Week3/ChangYeol/B1260.java, Week3/ChangYeol/B17471.java, Week3/ChangYeol/B1967.java, Week3/ChangYeol/B2468.java, Week3/ChangYeol/B2566.java, Week3/ChangYeol/B2606.java, Week3/ChangYeol/B2667.java, Week3/ChangYeol/B2738.java
1. **[10798 - 세로읽기](https://www.acmicpc.net/problem/10798)**  
- 주어진 단어들을 세로로 읽어 새로운 문자열을 생성합니다.
2. **[2738 - 행렬 덧셈](https://www.acmicpc.net/problem/2738)**  
- 두 개의 N×M 행렬을 더하는 프로그램을 작성합니다.
3. **[2566 - 최댓값](https://www.acmicpc.net/problem/2566)**  
- 9×9 크기의 격자에서 최댓값과 그 위치를 찾습니다.
코드 리뷰 부탁드립니다!
=> [Week3] 이창열 브론즈 제출

Week3/jaesung/B10798.java, Week3/jaesung/B11725.java, Week3/jaesung/B1260.java, Week3/jaesung/B17471.java, Week3/jaesung/B1967.java, Week3/jaesung/B2468.java, Week3/jaesung/B2566.java, Week3/jaesung/B2606.java, Week3/jaesung/B2667.java, Week3/jaesung/B2738.java
1.  세로읽기 (링크 : https://www.acmicpc.net/problem/10798)
- 2차원 배열에 입력을 저장하고, 각 열에 대해 행을 순회하며 세로읽기 수행.
2. 행렬 덧셈 (링크 : https://www.acmicpc.net/problem/2738)
- 첫번째 행렬을 입력받은 뒤, 첫번째 행렬 해당 원소에 두번째 행렬 원소 덧셈 수행.
3. 최댓값 (링크 : https://www.acmicpc.net/problem/2566)
- 배열 입력과 동시에 최댓값 판별을 진행하여 최댓값과 최댓값 원소의 행, 열을 갱신.
4. DFS와 BFS (링크 : https://www.acmicpc.net/problem/1260)
- 입력에 맞게 그래프를 구성하고 DFS와 BFS를 수행하며 현재 탐색 노드를 출력.
5.  바이러스(링크 : https://www.acmicpc.net/problem/2606)
- 1번 컴퓨터부터 bfs 혹은 dfs를 통해 1번에서 도달 가능한 컴퓨터 개수를 파악.
6. 안전 영역 (링크 : https://www.acmicpc.net/problem/2468)
- 2차원 배열을 순회하며 bfs를 수행하여 안전 영역의 최대 개수를 파악.
7. 단지번호붙이기 (링크 : https://www.acmicpc.net/problem/2667)
- 2차원 배열을 순회하며 bfs를 통해 이웃한 1을 값으로 갖는 원소를 확인하여 단지 수 파악.
8. 트리의 부모 찾기 (링크 : https://www.acmicpc.net/problem/11725)
- 트리의 루트 노드 1번에서부터 dfs를 수행하며 …
=> [Week3] 한재성 브론즈 실버 골드 제출

Week3/youngjae/B10798.java, Week3/youngjae/B11725.java, Week3/youngjae/B1260.java, Week3/youngjae/B17471.java, Week3/youngjae/B1967.java, Week3/youngjae/B2468.java, Week3/youngjae/B2566.java, Week3/youngjae/B2606.java, Week3/youngjae/B2667.java, Week3/youngjae/B2738.java
브론즈 문제
[10798 - 세로읽기](https://www.acmicpc.net/problem/10798)
최대 들어올 수 있는 사이즈로 배열 생성후, 값이 입력된 경우에만 읽어서 출력
[2738 - 행렬 덧셈](https://www.acmicpc.net/problem/2738)
2차원 배열 2개 만들어서 더한 후 출력
[2566 - 최댓값](https://www.acmicpc.net/problem/2566)
9×9 크기의 격자에서 최댓값과 그 위치를 찾습니다.
=> [Week3] 송영재 브론즈 제출 

Week3/강창민/B10798.java, Week3/강창민/B11725.java, Week3/강창민/B1260.java, Week3/강창민/B17471.java, Week3/강창민/B1967.java, Week3/강창민/B2468.java, Week3/강창민/B2566.java, Week3/강창민/B2606.java, Week3/강창민/B2667.java, Week3/강창민/B2738.java
1. **[10798 - 세로읽기](https://www.acmicpc.net/problem/10798)**  
- 최대 들어올 수 있는 사이즈로 배열 생성후, 값이 입력된 경우에만 읽어서 출력
2. **[2738 - 행렬 덧셈](https://www.acmicpc.net/problem/2738)**  
- 2차원 배열 2개 만들어서 더한 후 출력
3. **[2566 - 최댓값](https://www.acmicpc.net/problem/2566)**  
- 9×9 크기의 격자에서 최댓값과 그 위치를 찾습니다.
---
1. **[1260 - DFS와 BFS](https://www.acmicpc.net/problem/1260)**  
- DFS BFS를 구현하고 출력해봤습니다
2. **[2606 - 바이러스](https://www.acmicpc.net/problem/2606)**  
- DFS로 감염된 pc를 확인했습니다
3. **[2468 - 안전 영역](https://www.acmicpc.net/problem/2468)**  
- DFS로 상하좌우로 연결되어 있는 영역을 방문처리하고, 안전지대 개수 세기
4. **[2667 - 단지 번호 붙이기](https://www.acmicpc.net/problem/2667)**  
- DFS로 상하좌우로 연결되어 있는 영역을 방문처리하고 세대수 세고, 단지 개수 세기
5. **[11725 - 트리의 부모 찾기](https://www.acmicpc.net/problem/11725)**  
- DFS로 자식노드로 이동하며 조상노드의 번호를 따로 저장했습니다
=> [Week3] 강창민 브론즈 실버 제출

Week2/hyochang/B17609.java, Week2/hyochang/B2470.java, Week3/hyochang/B10798.java, Week3/hyochang/B11725.java, Week3/hyochang/B1260.java, Week3/hyochang/B17471.java, Week3/hyochang/B1967.java, Week3/hyochang/B2468.java, Week3/hyochang/B2566.java, Week3/hyochang/B2606.java, Week3/hyochang/B2667.java, Week3/hyochang/B2738.java
---
1.  세로읽기 (링크 : https://www.acmicpc.net/problem/10798)
- 2차원 배열을 만들고 배열 길이를 문자 길이에 맞추어 만듭니다.
- 이후 각 arr[]의 길이까지만 출력하도록 조건을 걸어서 인덱스 에러를 방지합니다.
2. 행렬 덧셈 (링크 : https://www.acmicpc.net/problem/2738) 
- 2차원 배열 2개로 입력을 받고 새로운 배열에 더한 값을 넣어 생성합니다.
3. 최댓값 (링크 : https://www.acmicpc.net/problem/2566)
- 값을 입력받으며 최댓값이 갱신 될 경우 최댓값과 해당 인덱스를 저장합니다.
4. DFS와 BFS(링크 : https://www.acmicpc.net/problem/1260)
- stack과 queue를 사용해서 해당 형식에 맞게 값을 출력합니다.
5. 바이러스(링크 : https://www.acmicpc.net/problem/2606)
- BFS 탐색으로 1번과 연결된 컴퓨터를 탐색하고 이후 방문여부를 확인했던 Boolean배열을 보며 true의 갯수 -1 만큼을 출력합니다.
6. 안전 구역 (링크 : https://www.acmicpc.net/problem/2468)
- 물의 높이를 0부터 가장 높은 높이까지 올라가며 BFS 탐색을 활용하여 안전 구역의 수를 구합니다.
7. 단지 번호 붙이기 (링크 : https://www.acmicpc.net/problem/2667)
- BFS탐색으로 집이 있는 경우 연결된 단지를 모두 탐색/탐색하며 가구수를 카운트후 리스트에 넣음
- 탐색이 종료되면 …
=> [Week3] 진효창 브론즈 실버 제출

Week3/KimSungHa/B10798.py, Week3/KimSungHa/B11725.py, Week3/KimSungHa/B1260.py, Week3/KimSungHa/B17471.java, Week3/KimSungHa/B1967.java, Week3/KimSungHa/B2468.py, Week3/KimSungHa/B2566.py, Week3/KimSungHa/B2606.py, Week3/KimSungHa/B2667.py
1. 문제1260 (링크: https://www.acmicpc.net/problem/1260)
- DFS와 BFS를 이용한 탐색
2. 문제2468 (링크: https://www.acmicpc.net/problem/2468)
- 2차원 배열에서 비가 내렸을 경우들 중 안전영역의 최대 갯수 도출
- 매 시도마다 visited 생성 및 수정, 이후 배열을 돌며 안전구역마다 탐색으로 안전구역 갯수 체크
3. 문제2566 (링크: https://www.acmicpc.net/problem/2566)
- 2차원 배열에서 최댓값과 해당 인덱스 추출
4. 문제2606 (링크: https://www.acmicpc.net/problem/2606)
- 비방향성 그래프를 입력 받고 기준 지점부터 dfs로 정답 도출
5. 문제2667 (링크: https://www.acmicpc.net/problem/2667)
- 배열을 돌며 dfs혹은 bfs로 단지 갯수 및 단지 내 건물 갯수 카운트 후 출력
6. 문제2738 (링크: https://www.acmicpc.net/problem/2738)
- 행렬을 각각 입력받고 각각을 돌며 행렬 요소 더해 새로운 리스트 생성
7. 문제10798 (링크: https://www.acmicpc.net/problem/10798)
- 특수문자를 포함하지 않는다는 점을 활용(아니면 어떻게 할지를 생각해 놓아야...) 빈칸을 *로 저장해 빈칸은 건너 뛰고 세로읽기. 분명 메모리를 더 아낄 방법이 있을 것 같은데...
8. 문제11725 (링크: …
=> [Week3] 김성하 3주차 제출

Week4/jaesung/B10448.java, Week4/jaesung/B10819.java, Week4/jaesung/B10971.java, Week4/jaesung/B1145.java, Week4/jaesung/B12100.java, Week4/jaesung/B14888.java, Week4/jaesung/B17142.java, Week4/jaesung/B1977.java, Week4/jaesung/B2231.java, Week4/jaesung/B3040.java, Week4/jaesung/B6054.java, Week4/jaesung/B9663.java
1.  분해합 (링크 : https://www.acmicpc.net/problem/2231)
- 입력 범위를 순회하여 분해합을 구하고, 생성자를 제일 먼저 확인한경우 출력하고 종료를 수행.
2. 완전제곱수 (링크 : https://www.acmicpc.net/problem/1977)
- 입력 범위를 순회하며 완전제곱수를 판별. 완전제곱수일 경우 가산, 최솟값이 아직 없을 경우 갱신.
3. 백설 공주와 일곱 난쟁이 (링크 : https://www.acmicpc.net/problem/3040)
- 배열 입력 과정에서 전체 합을 구하고, 이중 for문에서 서로 다른 인덱스의 키를 뺀 값이 100인 경우에 해당되는 두 인덱스를 도출.
4. 유레카 이론 (링크 : https://www.acmicpc.net/problem/10448)
- 삼중 for문을 순회하며 세 인덱스 i, j, k에 해당되는 삼각수를 더해 3개의 삼각수로 표현되는지 판별.
5.  적어도 대부분의 배수 (링크 : https://www.acmicpc.net/problem/1145)
- 입력 배열에서 가장 작은 값을 1씩 증가시키며 적어도 대부분의 배수인지 판별.
6. 연산자 끼워넣기 (링크 : https://www.acmicpc.net/problem/14888)
- 백트래킹을 통해 숫자 사이에 연산자를 배치하는 모든 경우의 수를 확인하며 최대, 최소값을 도출.
7. 차이를 최대로 (링크 : https://www.acmicpc.net/problem/10819)
- 백트래킹을 통해 가능한 모든 자리바꿈 배열(=순열)을 구성하고, 최댓값을 갱신.
8. …
=> [Week4] 한재성 브론즈 실버 골드 제출

Week4/gyumin/B10448.java, Week4/gyumin/B1145.java, Week4/gyumin/B14888.java, Week4/gyumin/B1977.java, Week4/gyumin/B2231.java, Week4/gyumin/B3040.java
이번주 문제 풀이
[2231 - 분해합](https://www.acmicpc.net/problem/2231)
- 브루트포스 기법을 활용해 해당 수를 만들 수 있는지 검증
[1977 - 완전제곱수](https://www.acmicpc.net/problem/1977)
- 모든 수의 제곱근을 구한 뒤 그 제곱근이 소숫점이 없는 지 확인
[3040 - 백설공주와 일곱 난쟁이](https://www.acmicpc.net/problem/3040)
- 무작위로 7명의 난쟁이를 골라 조건에 해당하는지 확인
[10448 - 유레카 이론](https://www.acmicpc.net/problem/10448)
- 해당 숫자를 모든 삼각수를 활용해 만들어보고 만들어 지는지 확인
[1145 - 적어도 대부분의 배수](https://www.acmicpc.net/problem/1145)
- 브루트포스 기법을 활용해 입력받은 수로 나누어 떨어지는지 확인하고 그 수가 3개 이상인지 확인
[14888 - 연산자 끼워넣기](https://www.acmicpc.net/problem/14888)
- 백트래킹 기법을 활용해 연산자 위치를 무작위로 바꾸어가며 풀이
- 백트래킹 구현은 dfs와 유사하게 재귀함수를 구현하되 방문 체크를 하는 것이 아닌 함수 호출 전에 선택 가능한 연산자 수를 줄이고 함수 호출 후 다시 연산자 수를 늘리는 방식으로 진행
=> 김규민 4주차 문제 풀이

Week4/Jimin/B10448.java, Week4/Jimin/B1145.java, Week4/Jimin/B1977.java, Week4/Jimin/B2231.java, Week4/Jimin/B3040.java
---
[10448 - 유레카 이론](https://www.acmicpc.net/problem/10448)
- for문 3개를 이용한 완전탐색 . . . 재귀로 풀다가 마지막 값이 자꾸 틀려서 for문 3개 돌려버림 
[2231 - 분해합](https://www.acmicpc.net/problem/2231)
- 범위가 굉장히 커서 완전탐색할 때 해당 수의 길이수 * 9 를 뺀 수부터 해당 수 까지 범위를 지정하여 조건에 맞는 수 찾음
[3040 - 백설공주와 일곱난쟁이](https://www.acmicpc.net/problem/3040)
- 완전탐색으로 일곱난쟁이가 아닌 두 난쟁이를 찾음
[1977 - 완전제곱수](https://www.acmicpc.net/problem/1977)
- 뒤에서부터 완전탐색하여 완전제곱수에 해당하면 더해주고 해당 수를 min에 저장
[1145 - 적어도 대부분의 배수](https://www.acmicpc.net/problem/1145)
- 2부터 완전탐색하여 조건에 맞는 수 찾음
- 재귀를 알고나서부터 완전탐색 문제를 풀 때 재귀를 사용하려고 시도하게 되는 것 같음
- 코드 리뷰 부탁드립니다 !
=> [Week4] 이지민 브론즈 제출

Week4/huimang/B10448.java, Week4/huimang/B10819.java, Week4/huimang/B10971.java, Week4/huimang/B1145.java, Week4/huimang/B12100.java, Week4/huimang/B14888.java, Week4/huimang/B17142.java, Week4/huimang/B1977.java, Week4/huimang/B2231.java, Week4/huimang/B3040.java, Week4/huimang/B9663.java
1. 분해합 (링크:https://www.acmicpc.net/problem/2231)
-  문자열을 잘라서 풀었습니다.
2. 적어도 대부분의 배수 (링크: https://www.acmicpc.net/problem/1145)
- while문, count, if문을 이용해서 count가 일정 조건을 맞출 때 까지 반복했습니다.
3. 백설공주와 일곱난쟁이 (링크: https://www.acmicpc.net/problem/3040)
-  전체 합 - 100 = 두 난쟁이의 키. 두 수를 더해서 난쟁이의 키가 되는 두 명을 찾는 방식으로 해결했습니다.
4. 완전제곱수 (링크: https://www.acmicpc.net/problem/1977)
- 두 수 사이를 1부터 i까지 반복을 하며 완전 제곱수인지 판단 하였습니다.
5. 유레카 이론 (링크: https://www.acmicpc.net/problem/10448)
- 먼저 가능한 수의 범위 만큼 배열을 초기화 한 후 거기서 세 수가 더했을 때 N이 되는지를 판단 하였습니다.
- 코드 리뷰 부탁드립니다!
- 프론트 공부 하기 싫 엉 용 ㅠ 화이팅. .다들..
=> [Week4] 김희망 브론즈 제출

Week4/Youngjae/B10448.java, Week4/Youngjae/B10819.java, Week4/Youngjae/B10971.java, Week4/Youngjae/B1145.java, Week4/Youngjae/B12100.java, Week4/Youngjae/B14888.java, Week4/Youngjae/B17142.java, Week4/Youngjae/B1977.java, Week4/Youngjae/B2231.java, Week4/Youngjae/B3040.java, Week4/Youngjae/B9663.java
브론즈
[10448 - 유레카 이론](https://www.acmicpc.net/problem/10448)
브루트 포스로 완전탐색
[2231 - 분해합](https://www.acmicpc.net/problem/2231)
브루트 포스로 완전탐색하면서 모든 수에 대한 생성자 유무 파악
[3040 - 백설공주와 일곱난쟁이](https://www.acmicpc.net/problem/3040)
브루트 포스로 완전탐색하면서 가짜 두명 찾고 가짜 두명의 모자 합을 뺀 합이 100인 경우 파악
[1977 - 완전제곱수](https://www.acmicpc.net/problem/1977)
브루트 포스로 완전탐색
[1145 - 적어도 대부분의 배수](https://www.acmicpc.net/problem/1145)
브루트 포스로 완전탐색
=> [Week4] 송영재 브론즈 제출
